using Microsoft.CodeAnalysis;

namespace DynamoDBGenerator.SourceGenerator.Extensions.CodeGeneration;

public static class ClassDeclarationExtensions
{
    public static string CreateClassWithContent(this ITypeSymbol type, Func<ITypeSymbol, string> classContent)
    {
        var nameSpace = type.ContainingNamespace.IsGlobalNamespace
            ? null
            : type.ContainingNamespace.ToString();

        return @$"// <auto-generated at {DateTime.Now:yyyy-MM-dd HH:mm:ss ""GMT""zzz}/>
using System.Collections.Generic;
using Amazon.DynamoDBv2.Model;
using System.Linq;

{(nameSpace is null ? null : $@"namespace {nameSpace}
{{")}
    partial class {type.Name}
    {{
        {classContent(type)}
    }}
{(nameSpace is null ? null : @"}
")}";
    }
}