using Microsoft.CodeAnalysis;

namespace DynamoDBGenerator.SourceGenerator.Extensions.CodeGeneration;

public static class ClassDeclarationExtensions
{
    public static string CreateNamespace(this ITypeSymbol type, string content)
    {
        var nameSpace = type.ContainingNamespace.IsGlobalNamespace
            ? null
            : type.ContainingNamespace.ToString();

        return @$"// <auto-generated at {DateTime.Now:yyyy-MM-dd HH:mm:ss ""GMT""zzz}/>
using System.Runtime.CompilerServices;
using System.Collections.Generic;
using Amazon.DynamoDBv2.Model;
using System.Linq;

{(nameSpace is null ? null : $@"namespace {nameSpace}
{{")}
    {content}
{(nameSpace is null ? null : @"}
")}";
    }

    public static string CreateClass(this ITypeSymbol type, string content)
    {
        return @$"partial class {type.Name}
    {{
        {content}
    }}
";
    }
}