using Microsoft.CodeAnalysis;
namespace DynamoDBGenerator.SourceGenerator.Extensions;

public static class CodeGenerationExtensions
{
    /// <summary>
    ///     Creates a namespace based on the type.
    /// </summary>
    public static string CreateNamespace(this ITypeSymbol type, in string content, TimeSpan duration)
    {
        var nameSpace = type.ContainingNamespace.IsGlobalNamespace
            ? null
            : type.ContainingNamespace.ToString();

        return @$"// <auto-generated | TimeStamp: {DateTime.Now:yyyy-MM-dd HH:mm:ss} | Duration {duration.ToString()}>
#nullable enable
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Amazon.DynamoDBv2.Model;
using DynamoDBGenerator;
using DynamoDBGenerator.Attributes;
using DynamoDBGenerator.Exceptions;
using DynamoDBGenerator.Internal;

{(nameSpace is null ? null : $@"namespace {nameSpace}
{{")}
    {content}
{(nameSpace is null ? null : @"}
")}";
    }

    /// <summary>
    ///     Creates a class based on the type.
    /// </summary>
    public static string CreateClass(this ITypeSymbol type, in string content, in int indentLevel = 0)
    {
        return CreateClass(Accessibility.Public, type.Name, in content, in indentLevel, isPartial: true);
    }

    public static string CreateClass(in Accessibility accessibility, in string className, in string content, in int indentLevel, in bool isPartial = false)
    {
        var indent = StringExtensions.Indent(indentLevel);
        return $@"{accessibility.ToCode()} sealed{(isPartial ? " partial" : null)} class {className}
{indent}{{
{content}
{indent}}}";
    }
    public static string CreateStruct(in Accessibility accessibility, in string structName, in string content, in int indentLevel, in bool isPartial = false, in bool isReadonly = false, bool isRecord = false)
    {
        var indent = StringExtensions.Indent(indentLevel);
        return $@"{indent}{accessibility.ToCode()}{(isPartial ? " partial" : null)}{(isReadonly ? " readonly" : null)}{(isRecord? " record" : null)} struct {structName}
{indent}{{
{content}
{indent}}}";
    }
}