name: Benchmarker
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  comparison:
    name: Comparison Marshalling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Run
        run: dotnet run --project tests/DynamoDBGenerator.SourceGenerator.Benchmarks --configuration 'Release' -- --exporters 'JSON' --filter '*Marshalling.Comparison*' --memory --job 'Default'
      - name: Store
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Comparison Marshalling
          tool: 'benchmarkdotnet'
          output-file-path: BenchmarkDotNet.Artifacts/results/DynamoDBGenerator.SourceGenerator.Benchmarks.Benchmarks.Marshalling.TemporalBenchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          benchmark-data-dir-path: 'benchmarks/marshalling/comparison'
          comment-on-alert: false
          fail-on-alert: false
          alert-comment-cc-users: '@inputfalken'
  temporal:
    name: Temporal Marshalling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Run
        run: dotnet run --project tests/DynamoDBGenerator.SourceGenerator.Benchmarks --configuration 'Release' -- --exporters 'JSON' --filter '*TemporalBenchmarks*' --memory --job 'Default'
      - name: Store
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Temporal Marshalling
          tool: 'benchmarkdotnet'
          output-file-path: BenchmarkDotNet.Artifacts/results/DynamoDBGenerator.SourceGenerator.Benchmarks.Benchmarks.Marshalling.TemporalBenchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          benchmark-data-dir-path: 'benchmarks/marshalling/temporal'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@inputfalken'
  primitve:
    name: Primitive Marshalling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Run
        run: dotnet run --project tests/DynamoDBGenerator.SourceGenerator.Benchmarks --configuration 'Release' -- --exporters 'JSON' --filter '*PrimitiveBenchmarks*' --memory --job 'Default'
      - name: Store
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Primitive Marshalling
          tool: 'benchmarkdotnet'
          output-file-path: BenchmarkDotNet.Artifacts/results/DynamoDBGenerator.SourceGenerator.Benchmarks.Benchmarks.Marshalling.PrimitiveBenchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: 'benchmarks/marshalling/primitive'
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@inputfalken'
  collection:
    name: Collection Marshalling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Run
        run: dotnet run --project tests/DynamoDBGenerator.SourceGenerator.Benchmarks --configuration 'Release' -- --exporters 'JSON' --filter '*CollectionBenchmarks*' --memory --job 'Default'
      - name: Store
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Collection Marshalling
          tool: 'benchmarkdotnet'
          output-file-path: BenchmarkDotNet.Artifacts/results/DynamoDBGenerator.SourceGenerator.Benchmarks.Benchmarks.Marshalling.CollectionBenchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          benchmark-data-dir-path: 'benchmarks/marshalling/collection'
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@inputfalken'
